[package]
name = "diag"
version = "0.6.1"
edition = "2021"
authors = ["Adam Szkoda <adaszko@gmail.com>"]
description = "Directed Acyclic Graphs with integer vertices represented as a Strictly Upper Triangular Matrix stored in a bit set"
homepage = "https://github.com/adaszko/diag"
repository = "https://github.com/adaszko/diag"
keywords = ["dag", "graph"]
license = "GPL-3.0"


[dependencies]
fixedbitset = "0.4"
quickcheck = { version = "1", optional = true }

[dev-dependencies]
quickcheck = "1"

[features]
default = ["qc"]
qc = ["quickcheck"]
